language: python

python:
  - 3.5
  - 3.6

before_install: pip install -r ./tests/fixtures/requirements.txt

install:
  - pwd
  - sudo apt-get install -y gettext libncurses5-dev libacl1-dev libgpm-dev
  - ( if [ ! -d ~/vim/bin ]; then git clone https://github.com/vim/vim /tmp/vim && cd /tmp/vim && ./configure ./configure --with-features=huge --enable-fail-if-missing --enable-pythoninterp --prefix=$HOME/vim && make && make install; fi )
  - export VIM_EXE=$HOME/vim/bin/vim
  - cd $HOME/build/heavenshell/vim-snowflake

cache:
  directories:
    - $HOME/vim

before_script:
  - $HOME/vim/bin/vim --version

script:
  - cd tests
  - ./run.sh
  - cd ..
