language: python

python:
  - 3.5
  - 3.6

before_install: pip install -r ./tests/fixtures/requirements.txt

install:
  - pwd
  - git clone https://github.com/vim/vim /tmp/vim
  - mkdir ~/bin
  - cd /tmp/vim
  - sudo apt-get install -y gettext libncurses5-dev libacl1-dev libgpm-dev
  - ./configure --with-features=huge --enable-fail-if-missing --enable-pythoninterp --prefix=$HOME/bin/vim
  - make && make install
  - export VIM_EXE=$HOME/bin/vim/bin/vim
  - cd $HOME/build/heavenshell/vim-snowflake

before_script:
  - $HOME/bin/vim/bin/vim --version

script:
  - cd tests
  - ./run.sh > /dev/null
  - cd ..
